#!/bin/bash
# try to find full path of this APP
set -o pipefail
__APP_FULLPATH="${BASH_SOURCE[0]}";
if [[ x"$__APP_FULLPATH" =~ / ]]; then
    # / is found in path, using readlink to expend to abslute path
    APP_FULLPATH=$(readlink -f "$__APP_FULLPATH");
else
    # / not found in path, try to find with which command
    APP_FULLPATH=$(which "$__APP_FULLPATH");
    # not in $PATH, try to find in current directory
    if [[ -z "$APP_FULLPATH" ]]; then
        APP_FULLPATH="$(pwd)/${__APP_FULLPATH}";
    fi
fi
if [[ ! -e "${APP_FULLPATH}" ]]; then
    echo "Cannot determine location of this script";
    exit 1;
fi

APP_DIR=$(dirname "${APP_FULLPATH}")
APP_NAME=$(basename "${APP_FULLPATH}")
HOOK_DIR=$(readlink -f "${APP_DIR}/../cixtools/hooks")
if [[ ! -e "${HOOK_DIR}" ]]; then
    echo "No hook found, ignore pre-commit check" >&2;
    exit 0;
fi

WORKTREE=$(git rev-parse --show-toplevel)
if [[ -z "${WORKTREE}" ]]; then
    echo "Error: not a git repository, quit $WORKTREE" >&2;
    exit 1;
fi
GIT_DIR=$(git rev-parse --git-dir)
if [[ -z "${GIT_DIR}" ]]; then
    echo "Error: not a git repository, quit $GIT_DIR" >&2;
    exit 1;
fi

if [[ ! -e "${WORKTREE}/.cix-ciconfig" ]]; then
    exit 0;  # no ci config found, skip silently
fi

set -e
cat "${WORKTREE}/.cix-ciconfig" |
grep '^pre-commit[[:space:]]*=' |
sed -e 's#^pre-commit[[:space:]]*=[[:space:]]*##g'|
while read script_name; do
    if [[ -z $(echo "${script_name}"|grep '^["'\'']?/') ]]; then
        echo eval "\"${HOOK_DIR}/\"${script_name} \"${WORKTREE}\" \"${GIT_DIR}\"" >&2;  # relative path to hooks/tools/
        eval "\"${HOOK_DIR}/\"${script_name} \"${WORKTREE}\" \"${GIT_DIR}\"";  # relative path to hooks/tools/
        if [[ $? -ne 0 ]]; then
            exit $?;  # quit if any hook failed
        fi
    else
        echo eval "${script_name} \"${WORKTREE}\" \"${GIT_DIR}\"" >&2;  # absolute path specified
        eval "${script_name} \"${WORKTREE}\" \"${GIT_DIR}\"";  # absolute path specified
        if [[ $? -ne 0 ]]; then
            exit $?;  # quit if any hook failed
        fi
    fi
done
